#!/usr/bin/env python3
"""Render every desktop colour fragment from one palette source.

GTK, Sway, Foot, Superfile, Waybar, Rofi and Swaylock use different formats,
but every value comes from palette.yml.

  render_palette.py green  build/green
  render_palette.py violet build/violet
  render_palette.py blue    build/blue
  render_palette.py red     build/red
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

THEME_TOKENS = (
    "base", "mantle", "surface", "overlay", "text", "subtext",
    "accent", "accent2", "ok", "warn", "bad",
)
DOMAIN_TOKENS = (
    "dom_clean", "dom_dev", "dom_lab", "dom_dirty", "dom_services",
)
ANSI_TOKENS = (
    "ansi4", "ansi5", "ansi6", "ansi12", "ansi13", "ansi14",
)
SURFACE_TOKENS = THEME_TOKENS + DOMAIN_TOKENS
TOKENS = SURFACE_TOKENS + ANSI_TOKENS
BANNER = "Generated by render_palette.py; do not edit by hand."


def resolved_colours(doc: dict, variant: str) -> dict[str, str]:
    # A theme may change appearance, but it may not redefine security identity.
    colours = dict(doc["variants"][variant])
    overlap = sorted(set(colours) & set(DOMAIN_TOKENS))
    if overlap:
        raise ValueError(f"variant {variant} overrides semantic domain tokens: {overlap}")
    colours.update(doc["domains"])
    return colours


def gtk_css(name: str, c: dict[str, str]) -> str:
    lines = [f"/* {BANNER} palette: {name} */"]
    lines += [f"@define-color hl_{t} {c[t]};" for t in SURFACE_TOKENS]
    return "\n".join(lines) + "\n"


def waybar_css(name: str, c: dict[str, str]) -> str:
    lines = [f"/* {BANNER} palette: {name} */"]
    lines += [f"@define-color hl_{t} {c[t]};" for t in SURFACE_TOKENS]
    return "\n".join(lines) + "\n"


def sway_config(name: str, c: dict[str, str]) -> str:
    lines = [f"# {BANNER} palette: {name}"]
    lines += [f"set $hl_{t} {c[t]}" for t in SURFACE_TOKENS]
    lines += [
        "",
        "# focused / unfocused / urgent borders derived from the tokens",
        "client.focused          $hl_accent  $hl_mantle  $hl_text    $hl_accent  $hl_accent",
        "client.unfocused        $hl_overlay $hl_base    $hl_subtext $hl_overlay $hl_overlay",
        "client.focused_inactive $hl_overlay $hl_base    $hl_subtext $hl_overlay $hl_overlay",
        "client.urgent           $hl_bad     $hl_mantle  $hl_text    $hl_bad     $hl_bad",
    ]
    return "\n".join(lines) + "\n"


def rofi_rasi(name: str, c: dict[str, str]) -> str:
    lines = [f"/* {BANNER} palette: {name} */", "* {"]
    lines += [f"    hl-{t.replace('_', '-')}: {c[t]};" for t in SURFACE_TOKENS]
    lines += [
        "    background-color: transparent;",
        "    text-color:       @hl-text;",
        "}",
    ]
    return "\n".join(lines) + "\n"


def foot_ini(name: str, c: dict[str, str]) -> str:
    def raw(token: str) -> str:
        return c[token].lstrip("#")
    lines = [
        f"# {BANNER} palette: {name}",
        "[colors-dark]",
        "alpha=0.72",
        f"foreground={raw('text')}",
        f"background={raw('base')}",
        f"cursor={raw('base')} {raw('accent')}",
        f"selection-foreground={raw('text')}",
        f"selection-background={raw('surface')}",
        f"regular0={raw('overlay')}",
        f"regular1={raw('bad')}",
        f"regular2={raw('ok')}",
        f"regular3={raw('warn')}",
        f"regular4={raw('ansi4')}",
        f"regular5={raw('ansi5')}",
        f"regular6={raw('ansi6')}",
        f"regular7={raw('subtext')}",
        f"bright0={raw('surface')}",
        f"bright1={raw('bad')}",
        f"bright2={raw('accent')}",
        f"bright3={raw('warn')}",
        f"bright4={raw('ansi12')}",
        f"bright5={raw('ansi13')}",
        f"bright6={raw('ansi14')}",
        f"bright7={raw('text')}",
    ]
    return "\n".join(lines) + "\n"


def swaylock_conf(name: str, c: dict[str, str]) -> str:
    """Emit the complete active swaylock configuration for one palette."""
    def raw(token: str) -> str:
        return c[token].lstrip("#")
    lines = [
        f"# {BANNER} complete swaylock theme. palette: {name}",
        "daemonize",
        "ignore-empty-password",
        "indicator-caps-lock",
        "indicator-radius=100",
        "indicator-thickness=8",
        "scaling=fill",
        "font=JetBrainsMono Nerd Font",
        f"color={raw('base')}",
        f"inside-color={raw('mantle')}f2",
        f"inside-clear-color={raw('warn')}dd",
        f"inside-ver-color={raw('ok')}dd",
        f"inside-wrong-color={raw('bad')}dd",
        f"ring-color={raw('accent')}",
        f"ring-clear-color={raw('warn')}",
        f"ring-ver-color={raw('ok')}",
        f"ring-wrong-color={raw('bad')}",
        f"key-hl-color={raw('accent2')}",
        f"bs-hl-color={raw('bad')}",
        "line-color=00000000",
        "line-clear-color=00000000",
        "line-ver-color=00000000",
        "line-wrong-color=00000000",
        "separator-color=00000000",
        f"text-color={raw('text')}",
        f"text-clear-color={raw('base')}",
        f"text-ver-color={raw('base')}",
        f"text-wrong-color={raw('base')}",
    ]
    return "\n".join(lines) + "\n"


WRITERS = {
    "hyperlab-palette-gtk.css": gtk_css,
    "hyperlab-palette-waybar.css": waybar_css,
    "hyperlab-palette.sway": sway_config,
    "hyperlab-palette.rasi": rofi_rasi,
    "hyperlab-palette-foot.ini": foot_ini,
    "hyperlab-palette-swaylock.conf": swaylock_conf,
}


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: render_palette.py VARIANT DIRECTORY", file=sys.stderr)
        return 2
    variant, outdir = argv[1], Path(argv[2])
    doc = yaml.safe_load(Path(__file__).with_name("palette.yml").read_text())
    if variant not in doc["variants"]:
        print(f"unknown variant: {variant} "
              f"(available: {', '.join(doc['variants'])})", file=sys.stderr)
        return 2
    colours = resolved_colours(doc, variant)
    missing = [t for t in TOKENS if t not in colours]
    if missing:
        print(f"missing tokens in variant {variant}: {missing}", file=sys.stderr)
        return 1

    outdir.mkdir(parents=True, exist_ok=True)
    for filename, writer in WRITERS.items():
        target = outdir / filename
        target.write_text(writer(variant, colours), encoding="utf-8")
        print(f"  {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
