#!/usr/bin/env python3
"""Structural contract for four palettes and public/personal wallpaper modes."""
from __future__ import annotations
import hashlib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def require(condition: bool, message: str) -> None:
    if not condition: raise SystemExit(f"desktop theme contract: {message}")
def text(relative: str) -> str: return (ROOT / relative).read_text(encoding="utf-8")
def main() -> int:
    sway = text("roles/host_desktop_sway/files/sway.config")
    for marker in (
        "privatestack-waybar toggle", "privatestack-theme cycle",
        "privatestack-theme mode-toggle", "privatestack-theme daemon",
        "privatestack-hyperlab-session",
        "/usr/share/backgrounds/privatestack/public/green/01.png",
    ): require(marker in sway, f"Sway integration missing: {marker}")
    theme = text("roles/host_desktop_sway/files/privatestack-theme.sh")
    for marker in (
        "readonly themes=(green violet blue red)", "public_wallpaper_count=20",
        "personal_wallpaper_count", "active_wallpaper_count",
        "public_wallpaper_root", "personal_wallpaper_root", "wallpaper_mode_file",
        "mode-toggle", "mode-json", "hyperlab-palette-swaylock.conf",
        "lock_index=$(( (desktop_index + 3) % count ))",
    ): require(marker in theme, f"theme controller missing: {marker}")
    palette_tasks = text("roles/host_desktop_sway/tasks/palette.yml")
    host_tasks = text("roles/host_desktop_sway/tasks/main.yml")
    host_defaults = text("roles/host_desktop_sway/defaults/main.yml")
    require(
        "hyperlab-palette-hyprland.lua" in host_defaults,
        "Hyprland palette is not published in the shared runtime pool",
    )
    for marker in (
        "Inspect the persisted runtime theme",
        "Resolve the active runtime palette",
        "host_desktop_sway_active_palette",
        "Refuse an invalid persisted runtime palette",
    ):
        require(marker in palette_tasks, f"runtime theme preservation missing: {marker}")
    require(
        'desktop_palette_fragments }}/{{ desktop_palette }}/{{ item.src }}'
        not in palette_tasks,
        "active palette copies must not force the repository default",
    )
    require(
        "superfile" not in palette_tasks.lower(),
        "retired Superfile palette still has active ownership",
    )
    require(
        "superfile" not in theme.lower(),
        "theme controller still copies retired Superfile assets",
    )
    require(
        "hyperlab-palette-gtk.css" in palette_tasks
        and "gtk-3.0/gtk.css" in host_tasks
        and "gtk-4.0/gtk.css" in host_tasks,
        "managed GTK palette is no longer the file-manager visual source of truth",
    )

    status = text("roles/host_desktop_sway/files/privatestack-swaybar-status.py")
    for variant in ("green", "violet", "blue", "red"):
        require(f'"{variant}"' in status, f"fallback Swaybar palette missing: {variant}")
    require('block("wallpaper"' in status and '"mode-toggle"' in status,
            "fallback wallpaper toggle missing")
    waybar = text("roles/host_desktop_sway/files/waybar.jsonc")
    require('"custom/wallpaper-mode"' in waybar and '"signal": 9' in waybar,
            "Waybar wallpaper-mode toggle missing")
    hashes: dict[str, Path] = {}
    for variant in ("green", "violet", "blue", "red"):
        files = sorted((ROOT / f"roles/host_desktop_sway/files/wallpapers/{variant}").glob("*.png"))
        require(len(files) == 20, f"{variant} does not contain twenty public wallpapers")
        for path in files:
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            require(digest not in hashes, f"duplicate wallpaper: {path} and {hashes.get(digest)}")
            hashes[digest] = path
            require(path.stat().st_size > 25000, f"wallpaper suspiciously small: {path}")
        lock = ROOT / f"roles/host_desktop_sway/files/palette/{variant}/hyperlab-palette-swaylock.conf"
        require(lock.is_file(), f"swaylock palette missing: {variant}")
        content = lock.read_text(encoding="utf-8")
        require("ring-color=" in content and "inside-wrong-color=" in content,
                f"swaylock colors incomplete: {variant}")
        hyprland = ROOT / (
            f"roles/host_desktop_sway/files/palette/{variant}/"
            "hyperlab-palette-hyprland.lua"
        )
        require(
            hyprland.is_file(),
            f"Hyprland palette missing: {variant}",
        )
        hyprland_content = hyprland.read_text(encoding="utf-8")
        require(
            "\\n" not in hyprland_content,
            f"Hyprland palette contains literal newline escapes: {variant}",
        )
        require(
            hyprland_content.splitlines()[1] == "return {"
            and hyprland_content.splitlines()[-1] == "}",
            f"Hyprland palette is not a Lua return-table module: {variant}",
        )
        for marker in (
            "Generated by render_palette.py; do not edit by hand.",
            "active_border = ",
            "inactive_border = ",
            "urgent_border = ",
            "dom_clean = ",
            "dom_dev = ",
            "dom_lab = ",
            "dom_dirty = ",
            "dom_services = ",
        ):
            require(
                marker in hyprland_content,
                f"Hyprland palette incomplete: {variant}: {marker}",
            )
    require("wallpapers/personal/" in text(".gitignore"),
            "personal wallpaper ignore rule missing")
    print("HyperLab four-theme and wallpaper-mode contract: OK")
    return 0
if __name__ == "__main__": raise SystemExit(main())
