#!/usr/bin/env python3
"""Keep development-process attribution out of public repository content."""

from __future__ import annotations

import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

# Split tokens deliberately: the guard must not contain the exact strings it
# rejects, otherwise it would fail on its own source.
FORBIDDEN = (
    "clau" + "de",
    "chat" + "gpt",
    "open" + "ai",
    "anth" + "ropic",
    "co" + "dex",
    "github " + "copilot",
    "a" + "i-" + "generated",
    "a" + "i " + "generated",
    "generated by " + "a" + "i",
    "a" + "i " + "assistant",
)

LOCAL_ONLY = {
    "HYPERLAB-CURRENT-HANDOFF.md",
}


def repository_paths() -> list[Path]:
    result = subprocess.run(
        [
            "git",
            "ls-files",
            "-c",
            "-o",
            "--exclude-standard",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )

    paths = []

    for relative in result.stdout.splitlines():
        if not relative:
            continue

        if relative in LOCAL_ONLY:
            continue

        path = ROOT / relative

        if path.is_file():
            paths.append(
                path
            )

    return paths


def readable_text(
    path: Path,
) -> str | None:
    data = path.read_bytes()

    if b"\0" in data:
        return None

    try:
        return data.decode(
            "utf-8"
        )
    except UnicodeDecodeError:
        return None


def main() -> int:
    failures = []

    for path in repository_paths():
        content = readable_text(
            path
        )

        if content is None:
            continue

        for number, line in enumerate(
            content.splitlines(),
            start=1,
        ):
            lowered = line.lower()

            for marker in FORBIDDEN:
                if marker in lowered:
                    failures.append(
                        (
                            path.relative_to(ROOT),
                            number,
                        )
                    )

    if failures:
        for path, line in failures:
            print(
                f"FAIL public process metadata: "
                f"{path}:{line}"
            )

        raise SystemExit(
            "public repository process hygiene contract failed"
        )

    print(
        "Public repository process hygiene contract: OK"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )
