include theme.conf

font_family JetBrainsMono Nerd Font
font_size 11.5

background_opacity 0.92
dynamic_background_opacity yes
confirm_os_window_close 0
enable_audio_bell no

window_padding_width 10
window_border_width 1pt
draw_minimal_borders yes

tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold

shell_integration enabled
allow_remote_control yes
listen_on unix:/tmp/kitty-guest-{kitty_pid}

map ctrl+shift+f kitten hints
map ctrl+shift+e kitten hints --type path
map ctrl+shift+u kitten unicode_input
map ctrl+shift+p kitten choose-files
map ctrl+shift+d kitten diff
