#!/usr/bin/env python3
"""Validate choices, emit group variables, render HTML, or set a value.

  choices.py check
  choices.py vars
  choices.py panel choices.html
  choices.py set NAME VALUE
"""
from __future__ import annotations

import html
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).parent
SOURCE = HERE / "choices.yml"
DECIDERS = {"sid", "measurement", "deferred"}


class Refused(Exception):
    pass


def load(path: Path = SOURCE) -> dict:
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict) or "choices" not in doc:
        raise Refused("choices.yml does not contain a `choices` key")
    return doc


def check(doc: dict) -> list[str]:
    problems: list[str] = []
    for name, entry in doc["choices"].items():
        for field in ("question", "value", "options", "affects", "decided_by"):
            if field not in entry:
                problems.append(f"{name}: missing `{field}`")
        options = entry.get("options") or {}
        if len(options) < 2:
            problems.append(f"{name}: at least two alternatives are required, found {len(options)}")
        value = entry.get("value")
        if options and str(value) not in {str(key) for key in options}:
            problems.append(
                f"{name}: value `{value}` is not one of "
                f"{sorted(str(key) for key in options)}"
            )
        if entry.get("decided_by") not in DECIDERS:
            problems.append(
                f"{name}: decided_by `{entry.get('decided_by')}` is not one of {sorted(DECIDERS)}"
            )
        if not entry.get("affects"):
            problems.append(f"{name}: `affects` is empty")
        for key, description in options.items():
            if not str(description).strip():
                problems.append(f"{name}/{key}: consequence is not described")
    return problems


def group_vars(doc: dict) -> str:
    lines = [
        "---",
        "# Generated by tools/choices/choices.py; source: tools/choices/choices.yml.",
        "# Edit the source, then regenerate this file.",
        "#",
        "#   python3 tools/choices/choices.py set <name> <value>",
        "#   python3 tools/choices/choices.py vars > group_vars/all/choices.yml",
        "",
    ]
    for name, entry in doc["choices"].items():
        lines.append(f"# {entry['question']}")
        lines.append(f"#   alternatives: {', '.join(str(key) for key in entry['options'])}")
        value = entry["value"]
        rendered = value if isinstance(value, int) else f'"{value}"'
        lines.append(f"{name}: {rendered}")
        lines.append(f"{name}_options: [{', '.join(repr(str(key)) for key in entry['options'])}]")
        lines.append("")
    return "\n".join(lines)


def panel(doc: dict) -> str:
    badges = {
        "sid": ("Selected by Sid", "#7ee787"),
        "measurement": ("Selected by test", "#7ee787"),
        "deferred": ("Deferred", "#9d9dc4"),
    }
    rows = []
    for name, entry in doc["choices"].items():
        label, colour = badges[entry["decided_by"]]
        options = []
        for key, description in entry["options"].items():
            active = str(key) == str(entry["value"])
            options.append(
                f'<li class="{"on" if active else "off"}">'
                f'<code>{html.escape(str(key))}</code>'
                f'{" <b>· active</b>" if active else ""}'
                f'<p>{html.escape(str(description).strip())}</p></li>'
            )
        files = "".join(
            f"<li><code>{html.escape(path)}</code></li>" for path in entry["affects"]
        )
        rows.append(
            f"""
  <section>
    <h2>{html.escape(entry['question'])}
      <span class="badge" style="border-color:{colour};color:{colour}">{label}</span>
    </h2>
    <p class="key"><code>{html.escape(name)}</code> = <b>{html.escape(str(entry['value']))}</b></p>
    <ul class="opts">{''.join(options)}</ul>
    <details><summary>Affected files</summary><ul class="files">{files}</ul></details>
  </section>"""
        )

    selected = sum(1 for entry in doc["choices"].values() if entry["decided_by"] != "deferred")
    deferred = sum(1 for entry in doc["choices"].values() if entry["decided_by"] == "deferred")
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>HyperLab · choices</title>
<style>
:root {{ --base:#0c1512; --mantle:#111d18; --surface:#1a2b23; --overlay:#2b453a;
         --text:#dcf3e4; --subtext:#93b3a3; --accent:#7ee787; }}
* {{ box-sizing:border-box }}
body {{ margin:0; padding:2rem 1.25rem; background:var(--base); color:var(--text);
        font:15px/1.55 ui-monospace,"JetBrains Mono",monospace; }}
main {{ max-width:60rem; margin:0 auto }}
h1 {{ font-size:1.5rem; margin:0 0 .25rem }}
.lede {{ color:var(--subtext); margin:0 0 2rem }}
section {{ background:var(--mantle); border:1px solid var(--overlay);
           border-radius:12px; padding:1rem 1.25rem; margin-bottom:1rem }}
h2 {{ font-size:1.05rem; margin:0 0 .5rem; display:flex; gap:.75rem;
      align-items:baseline; flex-wrap:wrap }}
.badge {{ font-size:.7rem; border:1px solid; border-radius:999px;
          padding:.1rem .55rem; white-space:nowrap }}
.key {{ color:var(--subtext); margin:0 0 .75rem; font-size:.85rem }}
.key b {{ color:var(--accent) }}
ul {{ list-style:none; margin:0; padding:0 }}
.opts li {{ background:var(--surface); border-left:3px solid var(--overlay);
            border-radius:6px; padding:.6rem .8rem; margin-bottom:.5rem }}
.opts li.on {{ border-left-color:var(--accent) }}
.opts p {{ margin:.35rem 0 0; color:var(--subtext); font-size:.85rem }}
.opts b {{ color:var(--accent) }}
code {{ color:var(--text) }}
details {{ margin-top:.5rem; font-size:.8rem; color:var(--subtext) }}
summary {{ cursor:pointer }}
.files li {{ padding:.15rem 0 }}
footer {{ color:var(--subtext); font-size:.8rem; margin-top:2rem;
          border-top:1px solid var(--overlay); padding-top:1rem }}
</style></head><body><main>
<h1>HyperLab · choices</h1>
<p class="lede">{len(doc['choices'])} decisions: {selected} selected, {deferred} deferred.
This page is generated from <code>choices.yml</code>; editing the HTML changes nothing.</p>
{''.join(rows)}
<footer>To change a choice:
<code>python3 choices.py set desktop_palette blue</code> &mdash;
then <code>python3 choices.py vars &gt; group_vars/all/choices.yml</code>.</footer>
</main></body></html>
"""


def set_value(name: str, value: str) -> None:
    doc = load()
    if name not in doc["choices"]:
        raise Refused(f"unknown choice: {name} (available: {', '.join(doc['choices'])})")
    options = {str(key) for key in doc["choices"][name]["options"]}
    if value not in options:
        raise Refused(f"{name}: `{value}` is not one of {sorted(options)}")
    text = SOURCE.read_text(encoding="utf-8")
    lines = text.split("\n")
    inside = False
    for index, line in enumerate(lines):
        if line.strip().startswith(f"{name}:") and line.startswith("  "):
            inside = True
            continue
        if inside and line.strip().startswith("value:"):
            indent = line[: len(line) - len(line.lstrip())]
            lines[index] = f"{indent}value: {value}"
            SOURCE.write_text("\n".join(lines), encoding="utf-8")
            return
        if inside and line and not line.startswith("    "):
            break
    raise Refused(f"{name}: the `value:` line was not found")


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    command = argv[1]
    try:
        if command == "check":
            problems = check(load())
            for item in problems:
                print(f"ERROR  {item}")
            doc = load()
            selected = sum(1 for entry in doc["choices"].values() if entry["decided_by"] != "deferred")
            deferred = sum(1 for entry in doc["choices"].values() if entry["decided_by"] == "deferred")
            print(
                f"choices: {len(doc['choices'])}  "
                f"selected: {selected}  deferred: {deferred}"
            )
            print("CHOICES: " + ("OK" if not problems else f"{len(problems)} errors"))
            return 1 if problems else 0
        if command == "vars":
            print(group_vars(load()), end="")
            return 0
        if command == "panel":
            target = Path(argv[2] if len(argv) > 2 else "choices.html")
            target.write_text(panel(load()), encoding="utf-8")
            print(f"written: {target}")
            return 0
        if command == "set":
            set_value(argv[2], argv[3])
            print(f"{argv[2]} = {argv[3]}")
            return 0
    except Refused as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 1
    except IndexError:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    print(f"unknown command: {command}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
