from ..commands import REGISTRY
from .base import Command

TEMPLATE = """# bash completion for hyperlabctl. Generated by `hyperlabctl completion`:
# regenerate it rather than editing, so a new subcommand completes by itself.
_hyperlabctl() {
    local commands="%(commands)s"
    local globals="--json --no-color --repo --version --help"
    if [[ ${COMP_CWORD} -eq 1 ]]; then
        mapfile -t COMPREPLY < <(compgen -W "${commands} ${globals}" -- "${COMP_WORDS[1]}")
        return 0
    fi
    case ${COMP_WORDS[1]} in
        vm)    mapfile -t COMPREPLY < <(compgen -W "list start stop inspect" -- "${COMP_WORDS[COMP_CWORD]}") ;;
        net)   mapfile -t COMPREPLY < <(compgen -W "list start stop" -- "${COMP_WORDS[COMP_CWORD]}") ;;
        image) mapfile -t COMPREPLY < <(compgen -W "list" -- "${COMP_WORDS[COMP_CWORD]}") ;;
        waybar|watch)
               mapfile -t COMPREPLY < <(compgen -W "--field summary trust ram gpu vms" -- "${COMP_WORDS[COMP_CWORD]}") ;;
        logs)  mapfile -t COMPREPLY < <(compgen -W "-n --lines --level error warn info debug" -- "${COMP_WORDS[COMP_CWORD]}") ;;
        *)     mapfile -t COMPREPLY < <(compgen -W "${globals}" -- "${COMP_WORDS[COMP_CWORD]}") ;;
    esac
    return 0
}
complete -F _hyperlabctl hyperlabctl
"""


class CompletionCommand(Command):
    name = "completion"
    help = "print a bash completion script for the subcommands that exist now"
    order = 90

    def run(self, args, ctx):
        print(TEMPLATE % {"commands": " ".join(sorted(REGISTRY))}, end="")
        return 0
