---
- name: Reload the udev rules
  ansible.builtin.command: udevadm control --reload
  changed_when: true

- name: Retrigger the kvmfr device
  ansible.builtin.command: udevadm trigger --subsystem-match=kvmfr --action=change
  changed_when: true

- name: Restart libvirtd for KVMFR cgroup policy
  ansible.builtin.systemd_service:
    name: "{{ looking_glass_libvirt_service }}"
    state: restarted
