---
hardware_probe_host_profile_report_path: "{{ host_profile_report_path }}"
hardware_probe_host_profile_report_dir: "{{ host_profile_report_path | dirname }}"
hardware_probe_unknown_report_path: "{{ hardware_probe_host_profile_report_dir }}/hardware-unknown.yml"
