#!/usr/bin/env python3
"""Render declarative HyperLab themes into consumer-specific fragments."""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path
from typing import Any

import yaml


TRUST_ORDER = (
    "host",
    "clean",
    "dev",
    "services",
    "dirty",
    "lab",
)

EXPECTED_TRUST_COLORS = {
    "host": "#8b949e",
    "clean": "#72f2a5",
    "dev": "#5b8cff",
    "services": "#35e4dd",
    "dirty": "#ff9d45",
    "lab": "#b184ff",
}

OUTPUTS = (
    "hyperlab-palette-quickshell.json",
    "hyperlab-palette-gtk.css",
    "hyperlab-palette-waybar.css",
    "hyperlab-palette.rasi",
    "hyperlab-palette-foot.ini",
    "hyperlab-palette-kitty.conf",
    "hyperlab-palette-hyprland.lua",
    "hyperlab-palette.sway",
    "hyperlab-palette-swaylock.conf",
    "hyperlab-rgb-map.json",
)

BANNER = "Generated by theme_render.py; do not edit by hand."


class ThemeRenderError(ValueError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ThemeRenderError(message)


def raw(value: str) -> str:
    return value.removeprefix("#")


def load(repo: Path, theme_id: str) -> tuple[dict[str, Any], dict[str, Any]]:
    root = repo / "themes" / theme_id

    manifest = yaml.safe_load(
        (root / "theme.yml").read_text(encoding="utf-8")
    )
    visual = yaml.safe_load(
        (root / "visual.yml").read_text(encoding="utf-8")
    )

    require(manifest["id"] == theme_id, "manifest/theme id mismatch")
    require(visual["theme"] == theme_id, "visual/theme id mismatch")

    trust = visual["trust"]["identities"]

    colours = {
        identity: trust[identity]["color"]
        for identity in TRUST_ORDER
    }

    require(
        colours == EXPECTED_TRUST_COLORS,
        "trust identity colours changed",
    )

    require(
        visual["appearance"]["focus"] == "#d0d7de",
        "generic focus token must remain neutral",
    )

    require(
        visual["keyboard_rgb"]["provider"]
        == "hyperlab-nitro-control",
        "unreviewed RGB provider",
    )

    return manifest, visual


def palette(visual: dict[str, Any]) -> dict[str, str]:
    appearance = visual["appearance"]
    trust = visual["trust"]["identities"]

    return {
        "name": "trust-model",
        "base": appearance["base"],
        "mantle": appearance["mantle"],
        "surface": appearance["surface"],
        "overlay": appearance["overlay"],
        "text": appearance["text"],
        "subtext": appearance["subtext"],
        "accent": appearance["focus"],
        "accent2": appearance["host_neutral"],
        "ok": "#3fb950",
        "warn": "#d29922",
        "bad": "#f85149",
        "dom_host": trust["host"]["color"],
        "dom_clean": trust["clean"]["color"],
        "dom_dev": trust["dev"]["color"],
        "dom_services": trust["services"]["color"],
        "dom_dirty": trust["dirty"]["color"],
        "dom_lab": trust["lab"]["color"],
    }


def quickshell(c: dict[str, str]) -> str:
    return json.dumps(
        c,
        indent=2,
        sort_keys=True,
    ) + "\n"


def css_tokens(c: dict[str, str], consumer: str) -> str:
    tokens = (
        "base",
        "mantle",
        "surface",
        "overlay",
        "text",
        "subtext",
        "accent",
        "accent2",
        "ok",
        "warn",
        "bad",
        "dom_host",
        "dom_clean",
        "dom_dev",
        "dom_services",
        "dom_dirty",
        "dom_lab",
    )

    lines = [
        f"/* {BANNER} theme: trust-model consumer: {consumer} */"
    ]

    lines.extend(
        f"@define-color hl_{token} {c[token]};"
        for token in tokens
    )

    return "\n".join(lines) + "\n"


def rofi(c: dict[str, str]) -> str:
    tokens = (
        "base",
        "mantle",
        "surface",
        "overlay",
        "text",
        "subtext",
        "accent",
        "accent2",
        "ok",
        "warn",
        "bad",
        "dom_host",
        "dom_clean",
        "dom_dev",
        "dom_services",
        "dom_dirty",
        "dom_lab",
    )

    lines = [
        f"/* {BANNER} theme: trust-model */",
        "* {",
    ]

    lines.extend(
        f"    hl-{token.replace('_', '-')}: {c[token]};"
        for token in tokens
    )

    lines.extend(
        [
            "    background-color: transparent;",
            "    text-color: @hl-text;",
            "}",
        ]
    )

    return "\n".join(lines) + "\n"


def foot(c: dict[str, str]) -> str:
    return f"""# {BANNER} theme: trust-model
[colors-dark]
alpha=0.84
foreground={raw(c['text'])}
background={raw(c['base'])}
cursor={raw(c['base'])} {raw(c['accent'])}
selection-foreground={raw(c['text'])}
selection-background={raw(c['surface'])}
regular0={raw(c['overlay'])}
regular1=f85149
regular2=3fb950
regular3=d29922
regular4=58a6ff
regular5=bc8cff
regular6=39c5cf
regular7={raw(c['subtext'])}
bright0={raw(c['surface'])}
bright1=ff7b72
bright2=56d364
bright3=e3b341
bright4=79c0ff
bright5=d2a8ff
bright6=56d4dd
bright7={raw(c['text'])}
"""


def kitty(c: dict[str, str]) -> str:
    return f"""# {BANNER} theme: trust-model
background {c['base']}
foreground {c['text']}
selection_background {c['surface']}
selection_foreground {c['text']}
cursor {c['accent']}
cursor_text_color {c['base']}
url_color #58a6ff
active_border_color {c['accent']}
inactive_border_color {c['overlay']}
active_tab_background {c['surface']}
active_tab_foreground {c['text']}
inactive_tab_background {c['mantle']}
inactive_tab_foreground {c['subtext']}
color0 {c['overlay']}
color1 #f85149
color2 #3fb950
color3 #d29922
color4 #58a6ff
color5 #bc8cff
color6 #39c5cf
color7 {c['subtext']}
color8 {c['surface']}
color9 #ff7b72
color10 #56d364
color11 #e3b341
color12 #79c0ff
color13 #d2a8ff
color14 #56d4dd
color15 {c['text']}
"""


def hyprland(c: dict[str, str]) -> str:
    lines = [
        f"-- {BANNER} theme: trust-model",
        "return {",
    ]

    for key in (
        "base",
        "mantle",
        "surface",
        "overlay",
        "text",
        "subtext",
        "accent",
        "accent2",
        "ok",
        "warn",
        "bad",
        "dom_host",
        "dom_clean",
        "dom_dev",
        "dom_services",
        "dom_dirty",
        "dom_lab",
    ):
        lines.append(f'    {key} = "{c[key]}",')

    lines.extend(
        [
            f'    active_border = "rgba({raw(c["accent"])}ff)",',
            f'    inactive_border = "rgba({raw(c["overlay"])}ff)",',
            f'    urgent_border = "rgba({raw(c["bad"])}ff)",',
            "}",
        ]
    )

    return "\n".join(lines) + "\n"


def sway(c: dict[str, str]) -> str:
    lines = [
        f"# {BANNER} theme: trust-model",
    ]

    for key in (
        "base",
        "mantle",
        "surface",
        "overlay",
        "text",
        "subtext",
        "accent",
        "accent2",
        "ok",
        "warn",
        "bad",
        "dom_host",
        "dom_clean",
        "dom_dev",
        "dom_services",
        "dom_dirty",
        "dom_lab",
    ):
        lines.append(f"set $hl_{key} {c[key]}")

    lines.extend(
        [
            "",
            "client.focused "
            "$hl_accent $hl_mantle $hl_text "
            "$hl_accent $hl_accent",
            "client.unfocused "
            "$hl_overlay $hl_base $hl_subtext "
            "$hl_overlay $hl_overlay",
            "client.focused_inactive "
            "$hl_overlay $hl_base $hl_subtext "
            "$hl_overlay $hl_overlay",
            "client.urgent "
            "$hl_bad $hl_mantle $hl_text "
            "$hl_bad $hl_bad",
        ]
    )

    return "\n".join(lines) + "\n"


def swaylock(c: dict[str, str]) -> str:
    return f"""# {BANNER} theme: trust-model
daemonize
ignore-empty-password
indicator-caps-lock
indicator-radius=100
indicator-thickness=8
scaling=fill
font=JetBrainsMono Nerd Font
color={raw(c['base'])}
inside-color={raw(c['mantle'])}f2
inside-clear-color={raw(c['warn'])}dd
inside-ver-color={raw(c['ok'])}dd
inside-wrong-color={raw(c['bad'])}dd
ring-color={raw(c['accent'])}
ring-clear-color={raw(c['warn'])}
ring-ver-color={raw(c['ok'])}
ring-wrong-color={raw(c['bad'])}
key-hl-color={raw(c['accent2'])}
bs-hl-color={raw(c['bad'])}
line-color=00000000
separator-color=00000000
text-color={raw(c['text'])}
"""


def rgb_map(visual: dict[str, Any]) -> str:
    rgb = visual["keyboard_rgb"]

    payload = {
        "version": 1,
        "theme": "trust-model",
        "source": rgb["source"],
        "provider": rgb["provider"],
        "capability": rgb["capability"],
        "zones": rgb["zones"],
        "zone_policy": rgb["zone_policy"],
        "brightness": rgb["brightness"],
        "update_policy": rgb["update_policy"],
        "identities": rgb["identities"],
    }

    return json.dumps(
        payload,
        indent=2,
        sort_keys=True,
    ) + "\n"


def outputs(visual: dict[str, Any]) -> dict[str, str]:
    c = palette(visual)

    return {
        "hyperlab-palette-quickshell.json": quickshell(c),
        "hyperlab-palette-gtk.css": css_tokens(c, "gtk"),
        "hyperlab-palette-waybar.css": css_tokens(c, "waybar"),
        "hyperlab-palette.rasi": rofi(c),
        "hyperlab-palette-foot.ini": foot(c),
        "hyperlab-palette-kitty.conf": kitty(c),
        "hyperlab-palette-hyprland.lua": hyprland(c),
        "hyperlab-palette.sway": sway(c),
        "hyperlab-palette-swaylock.conf": swaylock(c),
        "hyperlab-rgb-map.json": rgb_map(visual),
    }


def preview_html(
    repo: Path,
    visual: dict[str, Any],
) -> str:
    c = palette(visual)

    asset_root = (
        repo
        / "themes/assets/hyperlab-symbols-v1/images"
    )

    images = sorted(asset_root.glob("*.png"))

    require(len(images) == 10, "preview requires ten assets")

    cards = []

    for image in images:
        relative = (
            "../assets/hyperlab-symbols-v1/images/"
            + image.name
        )

        cards.append(
            f"""
            <article class="asset">
              <img src="{html.escape(relative)}"
                   alt="{html.escape(image.stem)}">
              <div class="asset-name">
                {html.escape(image.stem)}
              </div>
            </article>
            """
        )

    trust_chips = []

    labels = {
        "host": "HOST",
        "clean": "CLEAN",
        "dev": "DEV",
        "services": "SERVICES",
        "dirty": "DIRTY",
        "lab": "LAB",
    }

    for identity in TRUST_ORDER:
        color = EXPECTED_TRUST_COLORS[identity]

        trust_chips.append(
            f"""
            <div class="trust-chip">
              <span class="dot"
                    style="background:{color}"></span>
              {labels[identity]}
              <code>{color}</code>
            </div>
            """
        )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>HyperLab Trust Model Preview</title>
<style>
:root {{
  --base: {c['base']};
  --mantle: {c['mantle']};
  --surface: {c['surface']};
  --overlay: {c['overlay']};
  --text: {c['text']};
  --subtext: {c['subtext']};
  --focus: {c['accent']};
  --host: {c['dom_host']};
  --clean: {c['dom_clean']};
  --dev: {c['dom_dev']};
  --services: {c['dom_services']};
  --dirty: {c['dom_dirty']};
  --lab: {c['dom_lab']};
}}
* {{ box-sizing: border-box; }}
body {{
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at 50% -10%, #18212d 0, transparent 40%),
    var(--base);
  color: var(--text);
  font-family:
    "JetBrainsMono Nerd Font",
    "JetBrains Mono",
    monospace;
}}
.bar {{
  height: 37px;
  display: flex;
  align-items: center;
  gap: 7px;
  padding: 0 10px;
  background: rgba(7,9,13,.95);
  border-bottom: 1px solid var(--overlay);
}}
.ws {{
  width: 23px;
  height: 23px;
  border: 1px solid var(--overlay);
  border-radius: 7px;
  display: grid;
  place-items: center;
  color: var(--subtext);
  font-size: 10px;
}}
.ws.active {{
  border-color: var(--focus);
  background: var(--surface);
  color: var(--text);
}}
.pill {{
  height: 25px;
  display: flex;
  align-items: center;
  padding: 0 10px;
  border-radius: 8px;
  background: var(--surface);
  border: 1px solid var(--overlay);
  font-size: 11px;
}}
.brand {{
  border-color: var(--focus);
  font-weight: 700;
}}
.trust {{
  border-color: var(--dev);
}}
.spacer {{ flex: 1; }}
.metric {{
  color: var(--subtext);
  font-size: 10px;
}}
.control {{
  color: var(--text);
  background: var(--mantle);
}}
main {{
  max-width: 1500px;
  margin: 42px auto;
  padding: 0 28px 60px;
}}
h1 {{
  margin: 0;
  font-size: 28px;
}}
.lede {{
  max-width: 900px;
  color: var(--subtext);
  line-height: 1.65;
}}
.section {{
  margin-top: 36px;
}}
.trust-row {{
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}}
.trust-chip {{
  display: flex;
  align-items: center;
  gap: 9px;
  padding: 9px 12px;
  border: 1px solid var(--overlay);
  border-radius: 9px;
  background: var(--mantle);
}}
.trust-chip code {{
  color: var(--subtext);
}}
.dot {{
  width: 10px;
  height: 10px;
  border-radius: 50%;
}}
.gallery {{
  margin-top: 16px;
  display: grid;
  grid-template-columns:
    repeat(auto-fit, minmax(260px, 1fr));
  gap: 14px;
}}
.asset {{
  overflow: hidden;
  border: 1px solid var(--overlay);
  border-radius: 12px;
  background: var(--mantle);
}}
.asset img {{
  display: block;
  width: 100%;
  aspect-ratio: 1672 / 941;
  object-fit: cover;
}}
.asset-name {{
  padding: 10px 12px;
  color: var(--subtext);
  font-size: 11px;
}}
.note {{
  border-left: 3px solid var(--focus);
  padding: 12px 15px;
  background: var(--mantle);
  color: var(--subtext);
  line-height: 1.55;
}}
</style>
</head>
<body>
<header class="bar">
  <span class="ws active">1</span>
  <span class="ws">2</span>
  <span class="ws">3</span>
  <span class="ws">4</span>
  <span class="ws">5</span>
  <span class="ws">6</span>
  <span class="ws">7</span>
  <span class="ws">8</span>
  <span class="ws">9</span>

  <span class="pill brand">◆ HYPERLAB</span>
  <span class="pill trust">TRUST DEV</span>

  <span class="spacer"></span>

  <span class="metric">RAM 11.7G</span>
  <span class="metric">GPU VFIO</span>
  <span class="metric">VM 1</span>
  <span class="metric">42°C</span>
  <span class="metric">NET UP</span>
  <span class="metric">VOL 65%</span>
  <span class="metric">BAT 83%</span>

  <span class="pill control">KEY IT</span>
  <span class="pill control">THEME</span>
  <span class="pill control">CTL</span>
</header>

<main>
  <h1>HyperLab · Trust Model</h1>

  <p class="lede">
    Near-black host shell. Focus remains neutral. Trust colour appears
    only where the interface is communicating host-owned provenance.
    The keyboard follows the same identity through the reviewed four-zone
    Nitro broker.
  </p>

  <section class="section">
    <h2>Trust identities</h2>
    <div class="trust-row">
      {''.join(trust_chips)}
    </div>
  </section>

  <section class="section">
    <h2>Canonical symbols</h2>

    <div class="note">
      These ten assets are canonical, but no symbol is assigned to a trust
      identity yet. This gallery exists specifically so that mapping can be
      reviewed visually instead of inferred from filename or colour.
    </div>

    <div class="gallery">
      {''.join(cards)}
    </div>
  </section>
</main>
</body>
</html>
"""


def write_outputs(
    repo: Path,
    theme_id: str,
    outdir: Path,
    preview: Path | None,
) -> None:
    _manifest, visual = load(repo, theme_id)

    outdir.mkdir(parents=True, exist_ok=True)

    rendered = outputs(visual)

    require(
        tuple(sorted(rendered))
        == tuple(sorted(OUTPUTS)),
        "renderer output set changed",
    )

    for filename, content in rendered.items():
        target = outdir / filename
        target.write_text(content, encoding="utf-8")
        print(target)

    if preview is not None:
        preview.parent.mkdir(parents=True, exist_ok=True)

        # HTML fragments are indented for source readability. Strip only
        # incidental end-of-line whitespace before publishing the canonical
        # preview so generated output is deterministic and diff-clean.
        preview_content = "\n".join(
            line.rstrip(" \t")
            for line in preview_html(repo, visual).splitlines()
        ) + "\n"

        preview.write_text(
            preview_content,
            encoding="utf-8",
        )
        print(preview)


def main() -> int:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--repo",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    parser.add_argument("theme")
    parser.add_argument("outdir", type=Path)
    parser.add_argument("--preview", type=Path)

    args = parser.parse_args()

    try:
        write_outputs(
            args.repo,
            args.theme,
            args.outdir,
            args.preview,
        )
        return 0
    except (
        OSError,
        KeyError,
        TypeError,
        ThemeRenderError,
        yaml.YAMLError,
    ) as exc:
        print(
            f"HyperLab theme renderer: {exc}",
            file=sys.stderr,
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
