---
- name: Assemble an accelerated Arch Hyprland development workstation
  hosts: workstations
  become: true
  vars:
    guest_desktop_hyprland_nvidia_only: true
    guest_desktop_hyprland_headless_monitor: true
  roles:
    - workstation_kernel
    - workstation_access
    - guest_desktop_hyprland
    - dev_ide
    - guest_gpu_nvidia
    - role: guest_looking_glass_linux
      vars:
        guest_looking_glass_linux_experimental: true
